import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Page 1',
  description: 'This is Page 1',
};

// export const metadata: Metadata = {
//   title: 'Create Next App PAGE 2',
//   description: 'Generated by create next app',
// };

export default function Page1() {
  return (
    <main>
      <div className="flex justify-center items-center flex-col h-screen">
        <h1 className="text-2xl">Page 1</h1>
        <div className="mt-4">
          <Link href={'/'} className="text-xl">
            Back to Home Page
          </Link>
        </div>
      </div>
    </main>
  );
}
